name: Deploy docs to Netlify
on:
  - push
jobs:
  deploy_docs_to_netlify:
    name: Deploy docs to Netlify
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        env:
          cache-hash: ${{ hashFiles('pnpm-lock.yaml') }}
        with:
          path: ~/.pnpm-store
          key: pnpm-os_${{ runner.os }}-node_${{ matrix.node }}-lock_${{ env.cache-hash }}
          restore-keys: |
            pnpm-os_${{ runner.os }}-node_${{ matrix.node }}-
            pnpm-os_${{ runner.os }}-
            pnpm-

      - name: Pull dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.3.0
          run_install: true

      - name: Build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          cd ./apps/docs/
          npm run build

      - name: Package
        run: |
          cd ./apps/docs/
          npm run package:serverless
          mkdir -p .netlify/functions .netlify/publish
          cd .netlify
          cp -a ../.serverless/docs.zip functions/
          echo "process.env['MODE'] = 'serverless'; process.env['SSR_ONLY'] = 'true'; module.exports = require('./dist/server/index.js');" > docs.js
          zip -mv functions/docs.zip docs.js
          mv ../dist/public/entrypoints.json .
          cp -a ../dist/public/ publish/public
          mv entrypoints.json ../dist/public/
          echo "/* /.netlify/functions/docs/:splat 200" > publish/_redirects

      - name: Deploy
        uses: nwtgck/actions-netlify@v1.2.2
        with:
          publish-dir: './apps/docs/.netlify/publish/'
          functions-dir: './apps/docs/.netlify/functions/'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 2
